config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications'
  end

  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end
  resources :devices
  resources :teams

  if Setting.has_module?(:home)
    root to: 'home#index'
  else
    root to: 'topics#index'
  end
  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind', to: 'users#auth_unbind', as: 'unbind_account'

  mount RuCaptcha::Engine, at: '/rucaptcha'
  mount Notifications::Engine, at: '/notifications'
  mount StatusPage::Engine, at: '/'

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id', to: 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed', to: 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last', to: 'topics#recent', as: 'recent_topics'

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :favorites
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search', to: 'search#index', as: 'search'
  get '/search/users', to: 'search#users', as: 'search_users'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites do
      member do
        post :undestroy
      end
    end
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
    resources :stats
  end

  get 'api', to: 'home#api', as: 'api'
  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :api do
    namespace :v3 do
      get 'hello', to: 'root#hello'

      resource :devices
      resource :likes
      resources :nodes
      resources :photos
      resources :notifications do
        collection do
          post :read
          get :unread_count
          delete :all
        end
      end
      resources :topics do
        member do
          post :update
          get :replies
          post :replies
          post :follow
          post :unfollow
          post :favorite
          post :unfavorite
          post :ban
          post :action
        end
      end
      resources :replies do
        member do
          post :update
        end
      end
      resources :users do
        collection do
          get :me
        end
        member do
          get :topics
          get :replies
          get :favorites
          get :followers
          get :following
          get :blocked
          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end

      match '*path', to: 'root#not_found', via: :all
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end

  mount JasmineRails::Engine, at: '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get 'users/city/:id', to: 'users#city', as: 'location_users'
  get 'users', to: 'users#index', as: 'users'

  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: '', as: 'users' do
      member do
        # User only
        get :topics
        get :replies
        get :favorites
        get :notes
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
      end

      resources :team_users, path: 'people' do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match '*path', to: 'home#error_404', via: :all
end

app/models/note.rb
# 记事本
class Note < ApplicationRecord
  acts_as_cached version: 1, expires_in: 1.week

  belongs_to :user

  counter :hits, default: 0

  scope :recent_updated, -> { order(updated_at: :desc) }
  scope :published,      -> { where(publish: true) }

  validates :body, presence: true

  before_save :auto_set_value
  def auto_set_value
    unless body.blank?
      self.title = body.split("\n").first[0..50]
      self.word_count = body.length
    end
  end

  before_update :update_changes_count
  def update_changes_count
    self.changes_count = 0 if changes_count.blank?
    increment(:changes_count)
  end

  def display_title
    (title || '').gsub(/^[\#]+/, '')
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  require_module_enabled! :note

  before_action :authenticate_user!
  before_action :set_recent_notes, only: [:index, :show, :edit, :new, :create, :update]
  load_and_authorize_resource

  def index
    @notes = current_user.notes.recent_updated.paginate(page: params[:page], per_page: 20)
    fresh_when(@notes)
  end

  def show
    @note = Note.find(params[:id])
    @note.hits.incr(1)
  end

  def new
    @note = current_user.notes.build
  end

  def edit
    @note = current_user.notes.find(params[:id])
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.publish = note_params[:publish] == '1'
    if @note.save
      redirect_to(@note, notice: t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update_attributes(note_params)
      redirect_to(@note, notice: t('common.update_success'))
    else
      render action: 'edit'
    end
  end

  def preview
    out = Homeland::Markdown.call(params[:body])
    render plain: out
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    redirect_to(notes_url)
  end

  private

  def set_recent_notes
    @recent_notes = current_user.notes.recent.limit(10)
  end

  def note_params
    params.require(:note).permit(:title, :body, :publish)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def render_node_name(name, id)
    link_to(name, main_app.node_topics_path(id), class: 'node')
  end

  def note_title_tag(note, opts = {})
    opts[:limit] ||= 50
    return '' if note.blank?
    return '' if note.title.blank?
    truncate(note.title.delete('#'), length: opts[:limit])
  end
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note, html: { class: "" }) do |f| %>
    <%= render "shared/error_messages", target: @note %>

    <div class="edit-tools">
      <%= render "/shared/editor_toolbar" %>
    </div>

    <div class="form-group">

      <%= f.text_area :body, rows: 20, class: 'form-control topic-editor' %>

      <p class="help-block">
        <%= t("notes.please_use") %> <a href="<%= markdown_path %>" target="_blank">Markdown</a> <%= t("notes.document_format_to_write") %>
      </p>
    </div>

    <div class="form-group">
      <label class="control-label" for="note_publish"><%= f.check_box :publish %> <%= t("common.public")%> <span class="text-danger"><i class="fa fa-warning"></i> 除非你选择公开，否则此 Note 的所有内容将是保密的！<span></label>
    </div>

    <div class="form-actions">
      <div class="row">
        <div class="col-sm-3">
          <%= f.submit t("common.save"), class: "btn btn-primary btn-lg btn-block", 'data-disable-with' => t("common.saving") %>
        </div>
        <div class="col-sm-2">
          <%= link_to t("common.cancel"), notes_path, class: "btn btn-default btn-lg btn-block" %>
        </div>
      </div>
    </div>
<% end %>

app/views/notes/_sidebar.html.erb
<div class="sidebar col-md-3">
  <div class="panel panel-default">
    <div class="panel-body">
      <a href="<%= new_note_path %>" class="btn btn-success btn-block">新建 Note</a>
    </div>
    <div class="panel-footer"><a href="<%= notes_path %>">查看我的 <%= current_user.notes.count %> 条 Note...</a></div>
  </div>

  <% if @recent_notes.present? %>
  <div class="panel panel-default">
    <div class="panel-heading">我最近创建的 Note</div>
    <ul class="list-group">
      <% @recent_notes.each do |note| %>
        <li class="list-group-item">
          <%= link_to note.display_title, note %>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<% title_tag t('notes.edit_note') %>

<div class="row">
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>

  <%= render "sidebar" %>
</div>

app/views/notes/index.html.erb
<% title_tag t('menu.notes') %>
<div class="row">
  <div class="col-md-9">
    <div id="notes" class="panel panel-default">
      <div class="panel-heading">
        <%= t('menu.notes') %>
        <span class="total pull-right">
        已有 <%= current_user.notes.count %> 条 Note
        </span>
      </div>

      <div class="panel-body">
        <% if @notes.blank? %>
          <div style="text-align:center; padding:60px 0;">你还没有创建过一个文件。</div>
        <% else %>
          <% @notes.each do |note| %>
            <div class="media">
              <div class="media-body">
                <div class="media-heading">
                  <%= link_to note.display_title, note %>
                  <% if note.publish %>
                    <span class="label warning"><i class="fa fa-share-alt"></i> 公开</span>
                  <% end %>
                  <span class="opts pull-right">
                    <a href="<%= edit_note_path(note.id) %>"><i class="fa fa-pencil"></i></a>
                  </span>
                </div>
                <div class="info">
                  <%= note.word_count %> <%= t("notes.chars") %>, <%= sanitize t("notes.created_at", time: timeago(note.created_at)) %>, <%= note.changes_count %> <%= t("notes.times_edit") %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="panel-footer clearfix">
        <%= will_paginate @notes %>
      </div>
    </div>
  </div>

  <%= render "sidebar" %>
</div>

app/views/notes/new.html.erb
<% title_tag t('notes.new_note') %>

<div class="row">
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>

  <%= render "sidebar" %>
</div>

app/views/notes/show.html.erb
<% title_tag [@note.title, t('menu.notes')].join(' · ') %>

<div class="row">
  <div class="col-sm-9">
    <div id="notes" class="panel panel-default">
      <div class="panel-heading clearfix">
        <div class="info">
          共 <%= @note.word_count %> <%= t("notes.chars") %>
          • <%= user_name_tag(@note.user) if !owner? @note %>
          <%= l @note.created_at, format: :long %>
          • <%= @note.hits %> <%= t("common.read_times")%>
          • <%= @note.changes_count %> <%= t("notes.times_edit") %>
          <% if owner? @note %>
          <span class="opts pull-right">
            <%= link_to icon_tag("pencil"), edit_note_path(@note),  title: t("common.edit") %>
            <%= link_to icon_tag("trash"), note_path(@note), 'data-confirm' => t("common.confirm_delete"), method: :delete, title: t("common.confirm_delete") %>
          </span>
          <% end %>
        </div>
        <% if @note.publish %>
        <div class="links">
          <label><%= t("notes.page_link")%></label>
          <%= note_url(@note) %>
        </div>
        <% end %>
      </div>
      <div class="panel-body">
        <% if !@note.publish %>
        <i class="fa fa-lock text-success pull-right" title="此内容保密"></i>
        <% end %>
        <div class="markdown">
          <%= markdown(@note.body) %>
        </div>
      </div>
    </div>
  </div>

  <%= render "sidebar" %>
</div>