config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications'
  end

  resources :sites
  resources :pages, path: 'wiki' do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end
  resources :devices
  resources :teams

  if Setting.has_module?(:home)
    root to: 'home#index'
  else
    root to: 'topics#index'
  end
  match '/uploads/:path(![large|lg|md|sm|xs])', to: 'home#uploads', via: :get, constraints: {
    path: /[\w\d\.\/]+/i
  }

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  delete 'account/auth/:provider/unbind', to: 'users#auth_unbind', as: 'unbind_account'

  mount RuCaptcha::Engine, at: '/rucaptcha'
  mount Notifications::Engine, at: '/notifications'
  mount StatusPage::Engine, at: '/'

  resources :nodes do
    member do
      post :block
      post :unblock
    end
  end

  get 'topics/node:id', to: 'topics#node', as: 'node_topics'
  get 'topics/node:id/feed', to: 'topics#node_feed', as: 'feed_node_topics', defaults: { format: 'xml' }
  get 'topics/last', to: 'topics#recent', as: 'recent_topics'

  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      post :action
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :favorites
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get '/search', to: 'search#index', as: 'search'
  get '/search/users', to: 'search#users', as: 'search_users'

  namespace :admin do
    root to: 'home#index', as: 'root'
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users do
      member do
        delete :clean
      end
    end
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites do
      member do
        post :undestroy
      end
    end
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
    resources :applications
    resources :stats
  end

  get 'api', to: 'home#api', as: 'api'
  get 'markdown', to: 'home#markdown', as: 'markdown'

  namespace :api do
    namespace :v3 do
      get 'hello', to: 'root#hello'

      resource :devices
      resource :likes
      resources :nodes
      resources :photos
      resources :notifications do
        collection do
          post :read
          get :unread_count
          delete :all
        end
      end
      resources :topics do
        member do
          post :update
          get :replies
          post :replies
          post :follow
          post :unfollow
          post :favorite
          post :unfavorite
          post :ban
          post :action
        end
      end
      resources :replies do
        member do
          post :update
        end
      end
      resources :users do
        collection do
          get :me
        end
        member do
          get :topics
          get :replies
          get :favorites
          get :followers
          get :following
          get :blocked
          post :follow
          post :unfollow
          post :block
          post :unblock
        end
      end

      match '*path', to: 'root#not_found', via: :all
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: "pghero"
  end

  mount JasmineRails::Engine, at: '/specs' if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://localhost:3000/huacnlee
  get 'users/city/:id', to: 'users#city', as: 'location_users'
  get 'users', to: 'users#index', as: 'users'

  constraints(id: /[#{User::LOGIN_FORMAT}]*/) do
    resources :users, path: '', as: 'users' do
      member do
        # User only
        get :topics
        get :replies
        get :favorites
        get :notes
        get :blocked
        post :block
        post :unblock
        post :follow
        post :unfollow
        get :followers
        get :following
        get :calendar
      end

      resources :team_users, path: 'people' do
        member do
          post :accept
          post :reject
        end
      end
    end
  end

  match '*path', to: 'home#error_404', via: :all
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < Admin::ApplicationController
    before_action :set_topic, only: [:show, :edit, :update, :destroy, :undestroy, :suggest, :unsuggest]

    def index
      @topics = Topic.unscoped
      if params[:q].present?
        qstr = "%#{params[:q].downcase}%"
        @topics = @topics.where('title LIKE ?', qstr)
      end
      if params[:login].present?
        u = User.find_by_login(params[:login])
        @topics = @topics.where('user_id = ?', u.try(:id))
      end
      @topics = @topics.order(id: :desc)
      @topics = @topics.includes(:user).paginate(page: params[:page], per_page: 30)
    end

    def show
    end

    def new
      @topic = Topic.new
    end

    def edit
    end

    def create
      @topic = Topic.new(params[:topic].permit!)

      if @topic.save
        redirect_to(admin_topics_path, notice: 'Topic was successfully created.')
      else
        render action: 'new'
      end
    end

    def update
      if @topic.update_attributes(params[:topic].permit!)
        redirect_to(admin_topics_path, notice: 'Topic was successfully updated.')
      else
        render action: 'edit'
      end
    end

    def destroy
      @topic.destroy_by(current_user)

      redirect_to(admin_topics_path)
    end

    def undestroy
      @topic.update_attribute(:deleted_at, nil)
      redirect_to(admin_topics_path)
    end

    def suggest
      @topic.update_attribute(:suggested_at, Time.now)
      redirect_to(@topic, notice: "Topic:#{params[:id]} suggested.")
    end

    def unsuggest
      @topic.update_attribute(:suggested_at, nil)
      redirect_to(@topic, notice: "Topic:#{params[:id]} unsuggested.")
    end

    private

    def set_topic
      @topic = Topic.unscoped.find(params[:id])
    end
  end
end

app/controllers/api/v3/topics_controller.rb
module Api
  module V3
    class TopicsController < Api::V3::ApplicationController
      before_action :doorkeeper_authorize!, except: [:index, :show, :replies]
      before_action :set_topic, except: [:index, :create]

      # 获取话题列表，类似网站的 /topics 的结构，支持多种排序方式。
      #
      # GET /api/v3/topics
      #
      # @param type [String] 排序类型, default: `last_actived`, %w(last_actived recent no_reply popular excellent)
      # @param node_id [Integer] 节点编号，如果有给，就会只去节点下的话题
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      #
      # @return [Array<TopicTopicSerializer>]
      def index
        optional! :type, default: 'last_actived'
        optional! :node_id
        optional! :offset, default: 0
        optional! :limit, default: 20, values: 1..150

        params[:type].downcase!

        if params[:node_id].blank?
          @topics = Topic
          if current_user
            @topics = @topics.without_nodes(current_user.blocked_node_ids)
            @topics = @topics.without_users(current_user.blocked_user_ids)
          else
            @topics = @topics.without_hide_nodes
          end
        else
          @node = Node.find(params[:node_id])
          @topics = @node.topics
        end

        @topics = @topics.fields_for_list.includes(:user).send(scope_method_by_type)
        if %w(no_reply popular).index(params[:type])
          @topics = @topics.last_actived
        elsif params[:type] == 'excellent'
          @topics = @topics.recent
        end

        @topics = @topics.offset(params[:offset]).limit(params[:limit])
        render json: @topics
      end

      # 获取话题详情（不含回帖）
      #
      # GET /api/v3/topics/:id
      #
      # @param id [Integer] 话题编号
      # @return [TopicDetailSerializer] 此外 meta 里面包含当前用户对此话题的状态
      #
      # ```json
      # { followed: '是否已关注', liked: '是否已赞', favorited: '是否已收藏' }
      # ```
      def show
        @topic.hits.incr(1)
        meta = { followed: false, liked: false, favorited: false }

        if current_user
          # 处理通知
          current_user.read_topic(@topic)
          meta[:followed] = @topic.followed?(current_user.id)
          meta[:liked] = current_user.liked?(@topic)
          meta[:favorited] = current_user.favorited_topic?(@topic.id)
        end

        render json: @topic, serializer: TopicDetailSerializer, meta: meta
      end

      # 创建新话题
      #
      # POST /api/v3/topics
      #
      # @param title [String] 标题, [required]
      # @param node_id [Integer] 节点编号, [required]
      # @param body [Markdown] 格式的正文, [required]
      # @return [TopicDetailSerializer]
      def create
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied.new('当前登录的用户没有发帖权限，具体请参考官网的相关说明。') unless can?(:create, Topic)

        @topic = current_user.topics.new(title: params[:title], body: params[:body])
        @topic.node_id = params[:node_id]
        @topic.save!

        render json: @topic, serializer: TopicDetailSerializer
      end

      # 更新话题
      #
      # POST /api/v3/topics/:id
      #
      # @param title [String] 标题, [required]
      # @param node_id [Integer] 节点编号, [required]
      # @param body [String] Markdown 格式的正文, [required]
      # @return [TopicDetailSerializer]
      def update
        requires! :title
        requires! :body
        requires! :node_id

        raise AccessDenied unless can?(:update, @topic)

        if @topic.lock_node == false || admin?
          # 锁定接点的时候，只有管理员可以修改节点
          @topic.node_id = params[:node_id]

          if admin? && @topic.node_id_changed?
            # 当管理员修改节点的时候，锁定节点
            @topic.lock_node = true
          end
        end
        @topic.title = params[:title]
        @topic.body = params[:body]
        @topic.save!

        render json: @topic, serializer: TopicDetailSerializer
      end

      # 删除话题
      #
      # DELETE /api/v3/topics/:id
      def destroy
        raise AccessDenied unless can?(:destroy, @topic)
        @topic.destroy_by(current_user)
        render json: { ok: 1 }
      end

      # 获取话题的回帖列表
      #
      # GET /api/v3/topics/:id/replies
      #
      # @param offset [Integer] default: 0
      # @param limit [Integer] default: 20, range: 1..150
      # @return [Array<ReplySerializer]>
      def replies
        if request.post?
          create_replies
          return
        end

        params[:limit] ||= 20

        @replies = Reply.unscoped.where(topic_id: @topic.id).order(:id).includes(:user)
        @replies = @replies.offset(params[:offset].to_i).limit(params[:limit].to_i)

        @user_liked_reply_ids = []
        if current_user
          # 找出用户 like 过的 Reply，给 JS 处理 like 功能的状态
          @replies.each do |r|
            unless r.liked_user_ids.index(current_user.id).nil?
              @user_liked_reply_ids << r.id
            end
          end
        end

        render json: @replies, meta: { user_liked_reply_ids: @user_liked_reply_ids }
      end

      # 创建对话题的回帖
      #
      # POST /api/v3/topics/:id/replies
      #
      # @param body [String] 回帖内容，[required]
      # @return [ReplySerializer] 创建的回帖信息
      def create_replies
        doorkeeper_authorize!

        requires! :body

        raise AccessDenied.new('当前用户没有回帖权限，具体请参考官网的说明。') unless can?(:create, Reply)

        @reply = @topic.replies.build(body: params[:body])
        @reply.user_id = current_user.id
        @reply.save!
        render json: @reply
      end

      # 关注话题
      #
      # POST /api/v3/topics/:id/follow
      def follow
        @topic.push_follower(current_user.id)
        render json: { ok: 1 }
      end

      # 取消关注话题
      #
      # POST /api/v3/topics/:id/unfollow
      def unfollow
        @topic.pull_follower(current_user.id)
        render json: { ok: 1 }
      end

      # 收藏话题
      #
      # POST /api/v3/topics/:id/favorite
      def favorite
        current_user.favorite_topic(@topic.id)
        render json: { ok: 1 }
      end

      # 取消收藏话题
      #
      # POST /api/v3/topics/:id/unfavorite
      def unfavorite
        current_user.unfavorite_topic(@topic.id)
        render json: { ok: 1 }
      end

      # 屏蔽话题，移到 NoPoint 节点 (Admin only)
      # [废弃] 请用 POST /api/v3/topics/:id/action
      #
      # POST /api/v3/topics/:id/ban
      def ban
        raise AccessDenied.new('当前用户没有屏蔽别人话题的权限，具体请参考官网的说明。') unless can?(:ban, @topic)
        @topic.ban!
        render json: { ok: 1 }
      end

      # 更多功能
      # 注意类型有不同的权限，详见 GET /api/v3/topics/:id 返回的 abilities
      #
      # POST /api/v3/topics/:id/action?type=:type
      # @param type [String] 动作类型, ban - 屏蔽话题, excellent - 加精华, unexcellent - 去掉精华, close - 关闭回复, open - 开启回复
      def action
        raise AccessDenied unless can?(params[:type].to_sym, @topic)

        case params[:type]
        when 'excellent'
          @topic.excellent!
        when 'unexcellent'
          @topic.unexcellent!
        when 'ban'
          @topic.ban!
        when 'close'
          @topic.close!
        when 'open'
          @topic.open!
        end
        render json: { ok: 1 }
      end

      private

      def set_topic
        @topic = Topic.find(params[:id])
      end

      def scope_method_by_type
        case params[:type]
        when 'last_actived' then :last_actived
        when 'recent' then :recent
        when 'no_reply' then :no_reply
        when 'popular' then :popular
        when 'excellent' then :excellent
        else
          :last_actived
        end
      end
    end
  end
end

app/helpers/topics_helper.rb
require 'digest/md5'
module TopicsHelper
  def topic_favorite_tag(topic, opts = {})
    return '' if current_user.blank?
    opts[:class] ||= ''
    class_name = ''
    link_title = '收藏'
    if current_user && current_user.favorite_topic_ids.include?(topic.id)
      class_name = 'active'
      link_title = '取消收藏'
    end

    icon = raw(content_tag('i', '', class: 'fa fa-bookmark'))
    if opts[:class].present?
      class_name += ' ' + opts[:class]
    end

    link_to(raw("#{icon} 收藏"), '#', title: link_title, class: "bookmark #{class_name}", 'data-id' => topic.id)
  end

  def topic_follow_tag(topic, opts = {})
    return '' if current_user.blank?
    return '' if topic.blank?
    return '' if owner?(topic)
    opts[:class] ||= ''
    class_name = 'follow'
    class_name += ' active' if topic.follower_ids.include?(current_user.id)
    if opts[:class].present?
      class_name += ' ' + opts[:class]
    end
    icon = content_tag('i', '', class: 'fa fa-eye')
    link_to(raw("#{icon} 关注"), '#', 'data-id' => topic.id, class: class_name)
  end

  def topic_title_tag(topic, opts = {})
    return t('topics.topic_was_deleted') if topic.blank?
    if opts[:reply]
      index = topic.floor_of_reply(opts[:reply])
      path = main_app.topic_path(topic, anchor: "reply#{index}")
    else
      path = main_app.topic_path(topic)
    end
    link_to(topic.title, path, title: topic.title)
  end

  def topic_excellent_tag(topic)
    return '' unless topic.excellent?
    content_tag(:i, '', title: '精华帖', class: 'fa fa-diamond', data: { toggle: 'tooltip' })
  end

  def topic_close_tag(topic)
    return '' unless topic.closed?
    content_tag(:i, '', title: '问题已解决／话题已结束讨论', class: 'fa fa-check', data: { toggle: 'tooltip' })
  end
end

app/views/topics/_buttons.html.erb
<div class="opts">
  <% if !turbolinks_ios? %>
    <%= likeable_tag(@topic) %>
    <%= topic_follow_tag(@topic) %>
    <%= topic_favorite_tag(@topic) %>
  <% end %>

  <% if admin? %>
    <% if !@topic.suggested_at.blank? %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% else %>
    <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
    <% end %>
    <% if !@topic.excellent? %>
    <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic.id, type: 'excellent'), title: "设为精华帖" , method: "post", remote: true %>
    <% end %>

    <% if @topic.node_id != Node.no_point.id %>
    <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), action_topic_path(@topic.id, type: 'ban'), method: 'post', remote: true, title: "屏蔽此贴，移动到 NoPoint 节点" %>
    <% end %>
  <% end %>
  <span class="pull-right opts">
    <% if owner?(@topic) or admin? %>
    <% if can?(:close, @topic) %>
      <% if !@topic.closed? %>
        <%= link_to raw("<i class='fa fa-check'></i>"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
      <% else %>
        <%= link_to raw("<i class='fa fa-undo'></i>"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
      <% end %>
    <% end %>
    <%= link_to "", edit_topic_path(@topic), class: "fa fa-pencil", title: "修改本帖" %>
      <% if can?(:destroy, @topic) %>
      <%= link_to "", topic_path(@topic.id), method: :delete, remote: true, 'data-confirm': t("common.confirm_delete"), class: "fa fa-trash", title: "删除本帖" %>
      <% end %>
    <% end %>
  </span>
</div>

app/views/topics/_node_selector.html.erb
<div class="modal" id="node-selector" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>选择话题节点</strong>
      </div>
      <div class="modal-body">
        <%= render '/shared/index_sections' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/_related_topics.html.erb
<% cache([@topic, 'related_topic', Date.current]) do %>
  <% if @topic.related_topics.present? %>
    <div class="panel panel-default">
      <div class="panel-heading">相关话题</div>
      <ul class="list-group">
        <% @topic.related_topics.each do |topic| %>
          <li class="list-group-item"><%= link_to topic.title, topic %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/topics/_reply_form.html.erb
<%= render "/shared/editor_toolbar" %>
<%= form_for(Reply.new, remote: true, url: topic_replies_path(@topic)) do |f| %>

  <div class="form-group">
    <%= f.text_area :body, class: "topic-editor form-control", rows: "4", tabindex: "1" %>
  </div>
  <div class="submit-buttons">
    <button type="submit" id="reply-button" class="btn btn-primary" tabindex="2", data-disable-with='<%= t("topics.submit_reply") %>'><%= t("topics.submit_reply")%></button>
    <span class="help-inline" style="padding-left: 5px;" title="或者 Ctrl + Enter"><kbd>Command</kbd> + <kbd>Enter</kbd></span>

    <div class="pull-right"><a href="/markdown" target="_blank">排版说明</a></div>
  </div>
<% end %>

app/views/topics/_sidebar_for_topic_index.html.erb
<% if current_user && current_user.newbie? %>
<div class="panel panel-default">
  <div class="panel-heading">新手必读</div>
  <div class="panel-body">
    <%= raw Setting.newbie_notices %>
  </div>
</div>
<% else %>
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to t('topics.new_topic'), new_topic_path, class: 'btn btn-primary btn-block' %>
  </div>
</div>
<% end %>

<%= render "topics/sidebar_box_tips" %>

<%= raw Setting.topic_index_sidebar_html %>

<% cache(["sidebar_statistics",Time.now.strftime("%Y-%m-%d %H")]) do %>
<div class="panel panel-default">
  <div class="panel-heading"><%= t("common.statics")%></div>
  <ul class="list-group">
    <li class="list-group-item">社区会员: <%= User.unscoped.count %> 人</li>
    <li class="list-group-item">帖子数: <%= Topic.unscoped.count %> 个</li>
    <li class="list-group-item">回帖数: <%= Reply.unscoped.count %> 条</li>
  </ul>
</div>
<% end %>

app/views/topics/_topic_sidebar.html.erb
<div id="topic-sidebar" data-spy="affix" data-offset-bottom="65">
  <div class="panel panel-default">
    <div class="panel-body">
      <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
      <div class="buttons">
        <div class="group likes opts">
          <%= likeable_tag(@topic) %>
        </div>
        <div class="group">
          <div class="btn-group" role="group">
            <%= topic_follow_tag(@topic, class: 'btn btn-default') %>
            <%= topic_favorite_tag(@topic, class: 'btn btn-default') %>
          </div>
        </div>
      </div>
      <hr />
      <div class="group">
        <%= social_share_button_tag h("#{@topic.title} via: @#{Setting.twitter_id} ") %>
      </div>
      <hr />
      <div class="reply-buttons">
        <div class="total">
          共收到 <b><%= @topic.replies_count %></b> 条回复
        </div>
        <a href="#reply" class="btn btn-success btn-block btn-focus-reply">参与回复</a>
      </div>
      <hr />
      <div class="group opts">
        <% if admin? %>
          <div style="margin-bottom: 8px">
            <% if !@topic.suggested_at.blank? %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 取消"), unsuggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% else %>
            <%= link_to raw("<i class='fa fa-angle-double-up'></i> 置顶"), suggest_admin_topic_path(@topic), method: :post, remote: true %>
            <% end %>
            <% if !@topic.excellent? %>
            <%= link_to raw("<i class='fa fa-diamond'></i> 加精"), action_topic_path(@topic, type: 'excellent'), method: "post", remote: true %>
            <% end %>
            <% if @topic.node_id != Node.no_point.id %>
              <%= link_to raw("<i class='fa fa-ban'></i> 屏蔽"), action_topic_path(@topic, type: 'ban'), method: 'post', title: "屏蔽此贴，移动到 NoPoint 节点", remote: true %>
            <% end %>
          </div>
        <% end %>

        <% if owner?(@topic) or admin? %>
        <div>
          <% if can?(:close, @topic) %>
            <% if !@topic.closed? %>
              <%= link_to raw("<i class='fa fa-check'></i> 结束"), action_topic_path(@topic, type: 'close'), method: 'post', title: "关闭讨论／问题已解决", remote: true, data: { toggle: 'tooltip' } %>
            <% else %>
              <%= link_to raw("<i class='fa fa-undo'></i> 开启"), action_topic_path(@topic, type: 'open'), method: 'post', title: "重新开启话题", remote: true, data: { toggle: 'tooltip' } %>
            <% end %>
          <% end %>
          <%= link_to raw('<i class="fa fa-pencil"></i> 编辑'), edit_topic_path(@topic), title: "修改本帖" %>
          <% if can?(:destroy, @topic) %>
            <%= link_to raw('<i class="fa fa-trash"></i> 删除'), topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), title: "删除本帖", remote: true %>
          <% end %>
        </div>
        <% end %>
      </div>
      <a href="#" class="btn btn-block btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
    </div>
  </div>

  <div class="notify-updated">
    <a class="update" href="#"><i class="fa fa-bell-o"></i> <b>有新回复！</b>点击这里立即载入</a>
  </div>
</div>

app/views/topics/show.html.erb
<% title_tag @topic.title %>

<% content_for :scripts do %>
  <script type="text/javascript">
    Topics.topic_id = <%= @topic.id %>;
    <% if current_user && !@user_liked_reply_ids.blank? %>
    Topics.user_liked_reply_ids = [<%= @user_liked_reply_ids.join(",") %>];
    <% end %>
    $(document).ready(function(){
      <% if admin? %>
        $("#replies .reply a.edit").css('display','inline-block');
      <% elsif current_user %>
        $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display','inline-block');
      <% end %>
    })
  </script>
<% end %>

<div class="row">
  <div class="col-md-9">
    <div class="topic-detail panel panel-default">
      <%= render partial: "topics/topic_info", locals: { topic: @topic } %>

      <% if @topic.excellent? %>
        <div class="label-awesome">
          <i class="fa fa-diamond awesome"></i> 本帖已被设为精华帖！
          <% if admin? %>
          <div class="pull-right">
            <%= link_to icon_tag("close"), action_topic_path(@topic.id, type: 'unexcellent'), data: { method: "post", remote: true } %>
          </div>
          <% end %>
        </div>
      <% end %>

      <div class="panel-body markdown">
        <%= raw Setting.before_topic_html %>

        <article>
          <%= @topic.body_html %>
        </article>


        <%= raw Setting.after_topic_html %>
      </div>

      <div class="panel-footer clearfix">
        <%= render "buttons" %>
      </div>
    </div>

    <%= render partial: "ban_reason" %>

  <% if @replies.blank? %>
    <div class="no-result">
      <%= t("topics.no_replies") %>
    </div>
    <% else %>
    <div id="replies" class="panel panel-default" data-last-floor="<%= @replies.count(:all) %>">
      <div class="total panel-heading hide-ios">
        共收到 <b><%= @topic.replies_count %></b> 条回复
      </div>
      <div class="items panel-body">
        <%= cache([@topic, "raw:#{@show_raw}"]) do %>
          <%= render partial: "/replies/reply", collection: @replies %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if current_user %>
    <% if @topic.closed? %>
      <div class="alert alert-info">此话题已经于 <%= l @topic.closed_at, format: :long %> 关闭，不再接受任何回帖。</div>
    <% else %>
      <div id="reply" class="panel panel-default">
        <div class="panel-heading hide-ios">回帖</div>
        <div class="panel-body">
        <% if can? :create, Reply %>
          <%= render 'reply_form' %>
        <% else %>
          <div class="alert alert-info">
            当前设置新手用户不能在 22:00 ~ 9:00 发帖。
          </div>
        <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: "topics/translation/need_login_to_reply" %>
      </div>
    </div>
  <% end %>

  <%= render 'related_topics' %>
</div>

<% if !mobile? %>
  <div class="sidebar hidden-mobile col-md-3">
    <%= render 'topic_sidebar' %>
  </div>
<% else %>
  <div class="move-page-buttons">
    <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="top"><i class="fa fa-arrow-up"></i></a>
    <a href="#" class="btn btn-block btn-sm btn-move-page" data-type="bottom"><i class="fa fa-arrow-down"></i></a>
  </div>
<% end %>
</div>